export const T = {
  ko: {
    title: '성과 대시보드',
    loading: '로딩 중...',
    denied: '접근 권한이 없습니다',
    loadingData: '데이터 불러오는 중...',
    lastUpdate: '마지막 업데이트',
    refresh: '새로고침',
    autoRefresh: '자동',
    today: '오늘 실시간',
    pageViews: '랜딩',
    chart1d: '1일',
    chart3d: '3일',
    chartWeekly: '주간',
    chartMonthly: '월간',
    backTitle: '관리자로 돌아가기',
    trend: '추이',
    funnel: '퍼널',
    intentTitle: '관심도 분포',
    topCompanies: '상위 회사',
    countUnit: '개',
    dailyDetail: '일별 상세',
    total: '합계',
    expTitle: '실험 / 개선 기록',
    expAdd: '+ 추가',
    expCancel: '취소',
    expStartDate: '실험 시작일',
    expPlaceholder: '예: CTA 문구 변경, 랜딩 리디자인...',
    expSave: '저장',
    expDelete: '삭제',
    expDeleteConfirm: '이 실험 기록을 삭제하시겠습니까?',
    expEmpty: '아직 기록이 없습니다. 실험이나 개선 사항을 추가해보세요.',
    avg: '평균',
    tableHeaders: ['날짜', '전체', '광고', '자연유입', '가입', '회사', '홈→Jobs', '공고클릭', 'Jobs페이지뷰', '지원클릭', '스크랩', '채용지원'],
    metrics: {
      submissions: '제출', ad: '광고 (UTM)', organic: '자연유입',
      signups: '가입', jobClicks: '홈→Jobs', cardClicks: '공고클릭', jobApps: '채용지원', companies: '회사',
      jobsPageViews: 'Jobs페이지뷰', applyClicks: '지원클릭', saveClicks: '스크랩',
    },
    funnelEmpty: '스테이지를 클릭하여 퍼널을 구성하세요',
    funnelClear: '초기화',
    funnelOverall: '전체 전환율',
    funnelStep: 'Step',
    funnelDropped: '이탈',
    funnelOf: '전체 대비',
    funnelConv: '전환율',
    users: '가입자',
    usersTitle: '가입자 목록',
    usersTotal: '총 가입자',
    usersDownloadCsv: 'CSV 다운로드',
    usersEmail: '이메일',
    usersName: '이름',
    usersProvider: '가입 방법',
    usersCreatedAt: '가입일',
    usersLastSignIn: '마지막 로그인',
    usersLoading: '가입자 불러오는 중...',
    usersEmpty: '가입자가 없습니다.',
    applications: '지원자',
    appsTitle: '채용 지원 목록',
    appsTotal: '총 지원',
    appsEmpty: '지원 내역이 없습니다.',
    appsLoading: '지원 내역 불러오는 중...',
    appsJob: '포지션',
    appsCompany: '회사',
    appsApplicant: '지원자',
    appsEmail: '이메일',
    appsStatus: '상태',
    appsDate: '지원일',
    appsNote: '메모',
    appsResume: '이력서',
    appsSave: '저장',
    hrApproval: 'HR 승인',
    utm: 'UTM',
    utmTitle: 'UTM 캠페인 분석',
    utmSource: '소스 (utm_source)',
    utmCampaign: '캠페인 (utm_campaign)',
    utmContent: '콘텐츠 (utm_content)',
    utmViews: '방문',
    utmSubmissions: '제출',
    utmConvRate: '전환율',
    utmTotalViews: '총 UTM 방문',
    utmNoData: 'UTM 데이터가 아직 없습니다. 캠페인 링크로 방문이 들어오면 여기에 표시됩니다.',
  },
  en: {
    title: 'Performance Dashboard',
    loading: 'Loading...',
    denied: 'Access denied',
    loadingData: 'Loading data...',
    lastUpdate: 'Last updated',
    refresh: 'Refresh',
    autoRefresh: 'Auto',
    today: 'Today Live',
    pageViews: 'Landings',
    chart1d: '1D',
    chart3d: '3D',
    chartWeekly: 'W',
    chartMonthly: 'M',
    backTitle: 'Back to Admin',
    trend: 'Trend',
    funnel: 'Funnel',
    intentTitle: 'Intent Breakdown',
    topCompanies: 'Top Companies',
    countUnit: '',
    dailyDetail: 'Daily Detail',
    total: 'Total',
    expTitle: 'Experiments / Improvements',
    expAdd: '+ Add',
    expCancel: 'Cancel',
    expStartDate: 'Start date',
    expPlaceholder: 'e.g. CTA copy change, landing redesign...',
    expSave: 'Save',
    expDelete: 'Delete',
    expDeleteConfirm: 'Delete this experiment?',
    expEmpty: 'No records yet. Add an experiment or improvement.',
    avg: 'avg',
    tableHeaders: ['Date', 'Total', 'Ad', 'Organic', 'Sign-ups', 'Companies', 'Home→Jobs', 'Job Clicks', 'Jobs Page Views', 'Apply Clicks', 'Saves', 'Job Apps'],
    metrics: {
      submissions: 'Submissions', ad: 'Ad (UTM)', organic: 'Organic',
      signups: 'Sign-ups', jobClicks: 'Home→Jobs', cardClicks: 'Job Clicks', jobApps: 'Job Apps', companies: 'Companies',
      jobsPageViews: 'Jobs Page Views', applyClicks: 'Apply Clicks', saveClicks: 'Saves',
    },
    funnelEmpty: 'Click stages below to build your funnel',
    funnelClear: 'Clear',
    funnelOverall: 'Overall conversion',
    funnelStep: 'Step',
    funnelDropped: 'Dropped',
    funnelOf: 'of total',
    funnelConv: 'Conversion',
    users: 'Users',
    usersTitle: 'Sign-up Users',
    usersTotal: 'Total Users',
    usersDownloadCsv: 'Download CSV',
    usersEmail: 'Email',
    usersName: 'Name',
    usersProvider: 'Provider',
    usersCreatedAt: 'Signed Up',
    usersLastSignIn: 'Last Sign In',
    usersLoading: 'Loading users...',
    usersEmpty: 'No users found.',
    applications: 'Applications',
    appsTitle: 'Job Applications',
    appsTotal: 'Total',
    appsEmpty: 'No applications yet.',
    appsLoading: 'Loading applications...',
    appsJob: 'Position',
    appsCompany: 'Company',
    appsApplicant: 'Applicant',
    appsEmail: 'Email',
    appsStatus: 'Status',
    appsDate: 'Applied',
    appsNote: 'Note',
    appsResume: 'Resume',
    appsSave: 'Save',
    hrApproval: 'HR Approval',
    utm: 'UTM',
    utmTitle: 'UTM Campaign Analysis',
    utmSource: 'Source (utm_source)',
    utmCampaign: 'Campaign (utm_campaign)',
    utmContent: 'Content (utm_content)',
    utmViews: 'Views',
    utmSubmissions: 'Submissions',
    utmConvRate: 'Conv. Rate',
    utmTotalViews: 'Total UTM Views',
    utmNoData: 'No UTM data yet. Campaign visits will appear here.',
  },
}

export const METRICS_BASE = [
  { key: 'submissions', dataKey: 'submissions', color: '#374151', summaryKey: 'totalSubmissions' },
  { key: 'ad', dataKey: 'ad', color: '#4F46E5', summaryKey: 'adSubmissions' },
  { key: 'organic', dataKey: 'organic', color: '#10B981', summaryKey: 'organicSubmissions' },
  { key: 'signups', dataKey: 'signups', color: '#F59E0B', summaryKey: 'totalSignups' },
  { key: 'jobClicks', dataKey: 'jobClicks', color: '#F97316', summaryKey: 'totalJobClicks' },
  { key: 'cardClicks', dataKey: 'cardClicks', color: '#EC4899', summaryKey: 'totalCardClicks' },
  { key: 'jobsPageViews', dataKey: 'jobsPageViews', color: '#06B6D4', summaryKey: 'totalJobsPageViews' },
  { key: 'applyClicks', dataKey: 'applyClicks', color: '#D946EF', summaryKey: 'totalApplyClicks' },
  { key: 'saveClicks', dataKey: 'saveClicks', color: '#F472B6', summaryKey: 'totalSaveClicks' },
  { key: 'jobApps', dataKey: 'jobApps', color: '#EF4444', summaryKey: 'totalJobApps' },
  { key: 'companies', dataKey: 'companies', color: '#6B7280', summaryKey: 'uniqueCompanies' },
]

export const EXP_COLORS = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7', '#DDA0DD', '#98D8C8', '#F7DC6F']

export const DATA_KEYS = ['submissions', 'ad', 'organic', 'signups', 'companies', 'jobApps', 'jobClicks', 'cardClicks', 'jobsPageViews', 'applyClicks', 'saveClicks']

export const FUNNEL_TRACKING_START = '2026-05-09'

export const PRESET_FUNNELS = {
  ko: [
    { name: 'Jobs 채용 퍼널', desc: 'Jobs 페이지 방문부터 지원 완료까지', keys: ['jobsPageViews', 'cardClicks', 'applyClicks', 'jobApps'], since: FUNNEL_TRACKING_START },
    { name: '홈 → Jobs 전환', desc: '홈페이지 유입부터 Jobs 관심까지', keys: ['submissions', 'jobClicks', 'jobsPageViews', 'cardClicks'], since: FUNNEL_TRACKING_START },
    { name: '가입 & 지원', desc: '제출 → 가입 → 지원 전환', keys: ['submissions', 'signups', 'applyClicks', 'jobApps'], since: FUNNEL_TRACKING_START },
  ],
  en: [
    { name: 'Jobs Hiring Funnel', desc: 'From page visit to application', keys: ['jobsPageViews', 'cardClicks', 'applyClicks', 'jobApps'], since: FUNNEL_TRACKING_START },
    { name: 'Home → Jobs Conversion', desc: 'Home traffic to Jobs interest', keys: ['submissions', 'jobClicks', 'jobsPageViews', 'cardClicks'], since: FUNNEL_TRACKING_START },
    { name: 'Signup & Apply', desc: 'Submit → Signup → Apply flow', keys: ['submissions', 'signups', 'applyClicks', 'jobApps'], since: FUNNEL_TRACKING_START },
  ],
}

export const MAX_BAR_HEIGHT = 160

export const STATUS_OPTIONS = ['applied', 'viewed', 'reviewing', 'accepted', 'rejected']

export const STATUS_COLORS = {
  applied: { bg: '#E0E7FF', color: '#3730A3' },
  viewed: { bg: '#FEF3C7', color: '#92400E' },
  reviewing: { bg: '#DBEAFE', color: '#1E40AF' },
  accepted: { bg: '#D1FAE5', color: '#065F46' },
  rejected: { bg: '#FEE2E2', color: '#991B1B' },
}

export const HR_STATUS_COLORS = {
  pending: { bg: '#FEF3C7', color: '#92400E', label: { ko: '미입력', en: 'Pending' } },
  submitted: { bg: '#DBEAFE', color: '#1E40AF', label: { ko: '승인 대기', en: 'Submitted' } },
  approved: { bg: '#D1FAE5', color: '#065F46', label: { ko: '승인됨', en: 'Approved' } },
  rejected: { bg: '#FEE2E2', color: '#991B1B', label: { ko: '반려', en: 'Rejected' } },
}

export const COLORS = ['#4F46E5', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#6B7280']

export const inputStyle = {
  padding: '6px 10px', border: '1px solid #d1d5db', borderRadius: 6, fontSize: 13,
}

export const sectionStyle = {
  background: '#fff', border: '1px solid #e5e7eb', borderRadius: 12, padding: 20, marginBottom: 24,
}

export const sectionTitle = {
  fontSize: 16, fontWeight: 600, margin: '0 0 16px 0',
}
