-- Vietnamese IT Companies INSERT
-- Sources: topdev.vn (scraped pages 1-25) + knowledge base
-- Tier 1: 1000+ employees | Tier 2: 100-999 | Tier 3: <100 / startups
-- Run: psql $DATABASE_URL -f scripts/insert_companies.sql

INSERT INTO companies (name, tier) VALUES

-- ── TIER 1: Large corporations (1000+ employees) ──────────────────────────
('FPT Software', 1),
('FPT Corporation', 1),
('FPT Telecom', 1),
('Viettel Group', 1),
('Viettel Solutions', 1),
('Viettel Cyber Security', 1),
('VNPT Technology', 1),
('VNG Corporation', 1),
('Zalo (VNG)', 1),
('Zalopay (VNG)', 1),
('Vingroup Technology', 1),
('VinAI Research', 1),
('VinBigData', 1),
('Shopee Vietnam', 1),
('Lazada Vietnam', 1),
('Grab Vietnam', 1),
('Tiki Corporation', 1),
('MoMo (M_Service)', 1),
('VNPay', 1),
('Techcombank', 1),
('VPBank', 1),
('MB Bank', 1),
('ACB Bank', 1),
('Sacombank', 1),
('BIDV', 1),
('Vietcombank', 1),
('Vietinbank', 1),
('Agribank', 1),
('Harvey Nash Vietnam', 1),
('NashTech Vietnam', 1),
('TMA Solutions', 1),
('CMC Corporation', 1),
('CMC Telecom', 1),
('GlobalCyberSoft', 1),
('Rikkeisoft', 1),
('Gameloft Vietnam', 1),
('Bosch Vietnam', 1),
('Intel Products Vietnam', 1),
('Samsung R&D Vietnam', 1),
('Fujitsu Vietnam', 1),
('IBM Vietnam', 1),
('Oracle Vietnam', 1),
('Microsoft Vietnam', 1),
('SAP Vietnam', 1),
('Accenture Vietnam', 1),
('Deloitte Vietnam', 1),
('PwC Vietnam', 1),
('EY Vietnam', 1),
('KPMG Vietnam', 1),
('NTT DATA Vietnam', 1),

-- ── TIER 2: Mid-size companies (100–999 employees) ────────────────────────
('KMS Technology', 2),
('Axon Active Vietnam', 2),
('Logigear Vietnam', 2),
('Orient Software', 2),
('SotaTek', 2),
('Savvycom', 2),
('Katalon', 2),
('Amanotes', 2),
('Sky Mavis', 2),
('Got It Vietnam', 2),
('One Mount Group', 2),
('Gojek Vietnam', 2),
('Be Group', 2),
('Giaohangnhanh (GHN)', 2),
('Giaohangtietkiem (GHTK)', 2),
('Ahamove', 2),
('Logivan', 2),
('Ninja Van Vietnam', 2),
('J&T Express Vietnam', 2),
('Haravan', 2),
('KiotViet', 2),
('MISA JSC', 2),
('Base.vn', 2),
('Sapo Technology', 2),
('VCCorp', 2),
('VietnamWorks (Navigos)', 2),
('TopDev Vietnam', 2),
('TopCV Vietnam', 2),
('Chotot.com', 2),
('Foody.vn', 2),
('Now (Delivery)', 2),
('Baemin Vietnam', 2),
('Loship Vietnam', 2),
('Vexere', 2),
('Traveloka Vietnam', 2),
('Klook Vietnam', 2),
('ShopBack Vietnam', 2),
('Sendo', 2),
('VinID', 2),
('OnePay', 2),
('Finhay', 2),
('Coin98 Finance', 2),
('Ancient8', 2),
('Sipher', 2),
('KardiaChain', 2),
('Rikkei Finance', 2),
('ELSA Speak', 2),
('Topica Edtech Group', 2),
('HOCMAI', 2),
('CoderSchool Vietnam', 2),
('VinUniversity Tech', 2),
('Sun* Inc Vietnam', 2),
('GMO-Z.com RUNSYSTEM', 2),
('GMO-Z.com Vietnam Lab', 2),
('Luvina Software', 2),
('HBLAB Vietnam', 2),
('Pentalog Vietnam', 2),
('Amaris Vietnam', 2),
('Monstarlab Vietnam', 2),
('Designveloper', 2),
('Smartdev Vietnam', 2),
('Kyanon Digital', 2),
('VietSoftware International', 2),
('Adamo Software', 2),
('NAL Solutions', 2),
('AgileTech Vietnam', 2),
('Dwarves Foundation', 2),
('eZtek Software', 2),
('S3Corp', 2),
('Officience', 2),
('Endava Vietnam', 2),
('Capgemini Vietnam', 2),
('Softserve Vietnam', 2),
('Luxoft Vietnam', 2),
('DataArt Vietnam', 2),
('Epam Systems Vietnam', 2),
('Wipro Vietnam', 2),
('Infosys Vietnam', 2),
('HCL Technologies Vietnam', 2),
('TCS Vietnam', 2),
('ELCA Vietnam', 2),
('Toshiba Software Development Vietnam', 2),
('AS White Vietnam', 2),
('Propzy Vietnam', 2),
('Rever Vietnam', 2),
('iCheck Vietnam', 2),
('Bkav Corporation', 2),
('CyRadar', 2),
('VCS Vietnam', 2),
('Katalon Studio', 2),
('Holistics Data', 2),
('Wolffun Game', 2),
('Appota Group', 2),
('Funtap Vietnam', 2),
('Gamota Vietnam', 2),
('VTC Online', 2),
('SohaGame Vietnam', 2),
('Abivin Vietnam', 2),
('Pinetree Securities', 2),
('VNDIRECT Securities', 2),
('VCSC', 2),
('Manulife Vietnam Technology', 2),
('Prudential Vietnam Technology', 2),
('FWD Vietnam Technology', 2),
('AIA Vietnam Technology', 2),
('Viindoo Technology', 2),
('TOSY ROBOTICS', 2),
('DevSamurai', 2),
('Nimble', 2),
('Raksul Vietnam', 2),
('Clever Age Vietnam', 2),
('Ban Vien Company', 2),
('Gumi Vietnam', 2),
('TrueMoney Vietnam', 2),
('ZIGEXN VENTURA', 2),
('Paymentwall Vietnam', 2),
('HiveTech', 2),
('Thai Son Soft', 2),
('New Ocean', 2),
('NCCPLUS Vietnam', 2),
('Unicloud Group', 2),
('Bravesoft Vietnam', 2),
('POSCO DX Vietnam', 2),
('LOTTE INNOVATE Vietnam', 2),
('Secomm Solution', 2),
('Wonderlabs Vietnam', 2),
('Emerhub Vietnam', 2),
('Hotel Link Solutions', 2),
('Tinhvan Group', 2),
('30Shine Technology', 2),
('LINAGORA Vietnam', 2),
('Augen Software Group', 2),
('Inspius Vietnam', 2),
('Pan Pacific Tech Vietnam', 2),
('HDBank Technology', 2),
('TPBank Technology', 2),
('VIB Technology', 2),
('OCB Technology', 2),
('MSB Technology', 2),
('SHB Technology', 2),
('Techcom Securities Technology', 2),
('SSI Securities Technology', 2),
('VPBank Securities Technology', 2),
('F8 Online Education', 2),
('Edumall Vietnam', 2),
('ANTS Programmatic', 2),
('SG Fintech', 2),
('Trusting Social', 2),
('ELSAGA Technology', 2),
('Novaon Digital', 2),
('Ecomobi', 2),
('ITviec', 2),

-- ── TIER 3: Startups & small companies (<100 employees) ──────────────────
('IMIAI INC', 3),
('GGJungle', 3),
('FABA Technology', 3),
('Reputyze Asia', 3),
('Koh Young Vietnam', 3),
('Higher Identity Vietnam', 3),
('25 Inc.', 3),
('AREVO Vietnam', 3),
('Promanning', 3),
('DataHouse Vietnam', 3),
('USOL Vietnam', 3),
('Hanbiro Vietnam', 3),
('Viral Soft', 3),
('INTLABS', 3),
('ECO Vietnam', 3),
('Gobysend', 3),
('HEAD CAPITAL', 3),
('TFL Group', 3),
('VSS Vietnam', 3),
('AEG MEDIA', 3),
('Appfast', 3),
('MTI TECHNOLOGY', 3),
('IEC CORP', 3),
('Outsource Expert', 3),
('Filum AI', 3),
('BLogic Systems', 3),
('BIGMAX Vietnam', 3),
('Silicon Prime Labs', 3),
('WorkGot', 3),
('1CLOUDSTAR', 3),
('YOONG SOFTWARE', 3),
('EcomEasy Asia', 3),
('Elipsport', 3),
('UniBiz', 3),
('Ecentura', 3),
('Gamejam', 3),
('Moni Media', 3),
('LASTMILE WORKS', 3),
('Ritaworks', 3),
('HR1 Vietnam', 3),
('Toradex Vietnam', 3),
('Minerva Technology Solutions', 3),
('YMESE', 3),
('SHARK MARKET', 3),
('ZOOKIZ', 3),
('F&B IT Solutions (FBIS)', 3),
('CYBERLOTUS', 3),
('ZYYX Vietnam', 3),
('Combros', 3),
('RUE Inc.', 3),
('DTS Software Vietnam', 3),
('Nittsu System Vietnam', 3),
('TOSY Robotics', 3),
('Your.Rentals Vietnam', 3),
('Seal Commerce', 3),
('Blockpass Vietnam', 3),
('QTC TEK', 3),
('IPSIP Vietnam', 3),
('VTI Vietnam', 3),
('Avantility', 3),
('Inspire Lab Technology', 3),
('QUOINE Vietnam', 3),
('K&G Technology', 3),
('Bright Software Solution', 3),
('SQUAREONE Vietnam', 3),
('Rebus Software', 3),
('Mekong Soft', 3),
('GrapeCity Vietnam', 3),
('Prime Commerce', 3),
('P.A Vietnam', 3),
('Tech Moss', 3),
('Gomi Corp Vietnam', 3),
('FISOFT', 3),
('NEE TEK', 3),
('Ninasoft', 3),
('Ubitec', 3),
('FinX', 3),
('VIETCAP SECURITIES', 3),
('Emerhub', 3),
('BRAVOHR', 3),
('TwentyTech', 3),
('TECHVIET', 3),
('Waves Company', 3),
('Got It Inc', 3),
('ABHORIZON', 3),
('Unicloud Vietnam', 3),
('Bravesoft', 3),
('Paymentwall Inc', 3),
('HiveTech Vietnam', 3),
('Bibabo', 3),
('Interits', 3),
('IIST Vietnam', 3),
('KidsOnline', 3),
('Construct Digital Vietnam', 3),
('SNAP Innovations', 3),
('MooMoo Digital', 3),
('Pascalia Asia', 3),
('Nexsoft Vietnam', 3),
('Logistik Unicorp', 3),
('Best Logistics Technology', 3),
('Pasona Tech Vietnam', 3),
('MyKaki Vietnam', 3),
('OKXE Vietnam', 3),
('JV-IT TECHS', 3),
('AODIGY Vietnam', 3),
('Avatech Vietnam', 3),
('NVG Technology', 3),
('Manifera Software', 3),
('eDoctor Vietnam', 3),
('Foxnite', 3),
('Wisol Vietnam', 3),
('Tech Apollo', 3),
('Vinsofts', 3),
('BOOKINGBAY', 3),
('LangTech Vietnam', 3),
('DSCo Vietnam', 3),
('Quant Edge Vietnam', 3),
('Camino Information Software', 3),
('CellphoneS', 3),
('NAL Solutions Vietnam', 3),
('ADT Interactive Technology', 3),
('HQSOFT', 3),
('Chi Thanh Technology', 3),
('Endava Vietnam Office', 3),
('Nextify Vietnam', 3),
('Wize Solutions', 3),
('Secomm', 3),
('Hello Bacsi', 3),
('Syno International Vietnam', 3),
('Viec.Co', 3),
('Avantage Vietnam', 3),
('Pinetree Tech', 3),
('SG Tech Vietnam', 3),
('Ecentura Vietnam', 3),
('Carp Tech Corp', 3),
('Vina Aspire Technology', 3),
('VAIS Vietnam', 3),
('DataSeer Vietnam', 3),
('ThinkZone Ventures', 3),
('Phenikaa-X', 3),
('Dat Bike', 3),
('Selex Motors Vietnam', 3),
('Misfit Technologies', 3),
('Bizzi Vietnam', 3),
('Tikop Vietnam', 3),
('Infina Vietnam', 3),
('Anfin Vietnam', 3),
('Nami Foundation', 3),
('Monkey Junior', 3),
('Prep.vn', 3),
('DOL English', 3),
('Langmaster Vietnam', 3),
('Classbook Vietnam', 3),
('IvyPrep Vietnam', 3),
('Zuni Vietnam', 3),
('Educa Corporation', 3),
('Hahana.vn', 3),
('Vbee Vietnam', 3),
('Kyber Network', 3),
('Triip Protocol', 3),
('Oxalus Wallet', 3),
('Solv Protocol Vietnam', 3),
('Morphswap Vietnam', 3),
('1Office Vietnam', 3),
('ANTS Digital', 3),
('Appvity Vietnam', 3),
('KMS Labs', 3),
('KMS Solutions', 3),
('KMS Healthcare Vietnam', 3),
('Kobiton Vietnam', 3),
('Loship', 3),
('iPrice Vietnam', 3),
('Priceza Vietnam', 3),
('Websosanh Vietnam', 3),
('Vatgia.com', 3),
('5giay.vn', 3),
('Enbac.com', 3),
('Muaban.net', 3),
('Nhadat24h Vietnam', 3),
('Batdongsan.com.vn Tech', 3),
('Mogi.vn', 3),
('Tima Fintech', 3),
('Vaymuon.vn', 3),
('Payme Vietnam', 3),
('Vimo Vietnam', 3),
('VNPT TP.HCM', 3),
('Viettel Pay', 3),
('Vietguys', 3),
('Saigon Technology', 3),
('Ekotek Vietnam', 3),
('Designveloper Vietnam', 3),
('Pacific Technology Vietnam', 3),
('CodeBase Vietnam', 3),
('Innodata Vietnam', 3),
('Sigma Solutions Vietnam', 3),
('Converse Vietnam Tech', 3),
('Techmaster Vietnam', 3),
('Viking Education Vietnam', 3),
('Cyberlearn Vietnam', 3),
('Clevai Vietnam', 3),
('BookDoc Vietnam', 3),
('LIXI Technologies', 3),
('TrueMoney', 3),
('iSofHH', 3),
('Tinhvan Software', 3),
('Pyramid Consulting Vietnam', 3),
('Reksut Vietnam', 3),
('Smartlog Vietnam', 3),
('Oivan Vietnam', 3),
('Emobi Games Vietnam', 3),
('Fabysa Vietnam', 3),
('VietGuys Tech', 3),
('Strikingly Vietnam', 3),
('Katalon Inc', 3),
('Kyber Capital', 3),
('TomoChain', 3),
('ELSA Corp Vietnam', 3),
('Jobstreet Vietnam', 3),
('CareerBuilder Vietnam', 3),
('Navigos Group', 3),
('CyberSecurity Vietnam', 3),
('Athena Security Vietnam', 3),
('EagleEye Networks Vietnam', 3),
('BKCS Vietnam', 3),
('VinCSS Vietnam', 3),
('Gimasys Vietnam', 3),
('CloudCMS Vietnam', 3),
('GrapeCity Solutions', 3),
('InApps Technology', 3),
('Saola Digital', 3),
('Sotatek Blockchain', 3),
('FTI Consulting Vietnam', 3),
('Neurond AI Vietnam', 3),
('DeepCare AI Vietnam', 3),
('Trusting Social Vietnam', 3),
('VNG AI Lab', 3),
('Cinnamon AI', 3),
('KMS AI', 3),
('Pixta Vietnam', 3),
('Fossil Group Vietnam', 3),
('USAID Vietnam Tech', 3),
('Stradex Vietnam', 3),
('Miraway Vietnam', 3),
('SmartOSC', 3),
('Teko Vietnam', 3),
('OnPoint Vietnam', 3),
('Baso Vietnam', 3),
('Viet Solutions', 3),
('EzSOFT Vietnam', 3),
('Orenda Vietnam', 3),
('Zion Corporation Vietnam', 3),
('Paxos Vietnam', 3),
('OmiCRM', 3),
('Getfly CRM', 3),
('BRAVO Software', 3),
('Fast Software Vietnam', 3),
('Effect Vietnam', 3),
('Splus Software Vietnam', 3),
('CTS Software Vietnam', 3),
('BambooHR Vietnam', 3),
('Nhanh.vn', 3),
('Haravan Vietnam', 3),
('KiotViet Tech', 3),
('POS365 Vietnam', 3),
('CUKCUK Vietnam', 3),
('iPos Vietnam', 3),
('CloudPOS Vietnam', 3),
('Vietstock Technology', 3),
('Fiin Group Vietnam', 3),
('WiGroup Vietnam', 3),
('StockBook Vietnam', 3),
('Saigon Innovation Hub', 3),
('QTSC Vietnam', 3),
('Codemi Vietnam', 3),
('Suntech Vietnam', 3),
('Pixelz Vietnam', 3),
('VertexHQ Vietnam', 3),
('Byte Orbit Vietnam', 3),
('Gaotek Vietnam', 3),
('InApps Tech', 3),
('DevMakers Vietnam', 3),
('CodeForViet', 3),
('TechX Vietnam', 3),
('Nashtech Labs', 3),
('Lotus Fintech', 3),
('GreenTech Vietnam', 3),
('SmartCity Vietnam', 3),
('Vietdata', 3),
('DataViet', 3),
('AIViet', 3),
('FinTechX Vietnam', 3),
('RegTech Vietnam', 3),
('InsurTech Vietnam', 3),
('PropTech Vietnam', 3),
('AgriTech Vietnam', 3),
('HealthTech Vietnam', 3),
('EduTech Vietnam', 3),
('LogiTech Vietnam', 3),
('CleanTech Vietnam', 3)

ON CONFLICT (name) DO NOTHING;
