import { createClient } from '@supabase/supabase-js'
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY)

const t = {}
t['68e511a8-7b55-4237-a6aa-f9c1538c81d3'] = 'Betching is redefining veterinary clinic operations with electronic charting and healthcare platform solutions for the growing pet care industry.\n\n[Responsibilities]\n- Design and execute QA strategies for veterinary platform\n- Develop and maintain automated test suites\n- Perform functional, regression, and integration testing\n\n[Requirements]\n- QA engineering experience\n- Test automation framework experience\n- Understanding of software testing methodologies'
t['da14d4bb-fcc2-48e5-87bb-565c0a016b3e'] = 'Betching innovates veterinary clinic management with electronic charting and pet healthcare solutions.\n\n[Responsibilities]\n- Design and develop backend services\n- Build scalable APIs and microservices\n- Database design and optimization\n\n[Requirements]\n- Backend development experience\n- Modern backend frameworks proficiency\n- Database design and SQL optimization'
t['9c3eb23d-ccb0-415f-a7be-0ef057f0ec57'] = 'Vidacs (BDACS) is a core infrastructure provider in Koreas digital asset market, building institutional-grade custody and settlement solutions.\n\n[Responsibilities]\n- Design Web3 backend systems and blockchain integrations\n- Build smart contract interaction layers\n- Develop custody and settlement backends\n\n[Requirements]\n- Backend experience with blockchain/Web3\n- Ethereum, smart contracts, DeFi understanding\n- Proficiency in Node.js, Go, or Rust'
t['fdfaaf86-70d3-40f2-9581-1f6b7decf41d'] = 'Vidacs provides institutional-grade digital asset custody and settlement infrastructure.\n\n[Responsibilities]\n- Lead QA strategy for digital asset products\n- Design test plans for financial systems\n- Build automated testing pipelines\n\n[Requirements]\n- 5+ years QA experience in fintech\n- Test automation expertise\n- Financial systems and compliance understanding'
t['17a8c692-98ba-4640-a0a7-7c0c6e328c1d'] = 'Vidacs builds institutional digital asset infrastructure for custody and settlement.\n\n[Responsibilities]\n- Define product roadmap and priorities\n- Translate business requirements to technical specs\n- Coordinate cross-functional teams\n\n[Requirements]\n- Product management in fintech or blockchain\n- Technical understanding of software development\n- Data-driven decision making'
t['2bc07670-817c-46ef-afd3-029a48fa731a'] = 'Vidacs provides digital asset infrastructure for institutional custody and settlement.\n\n[Responsibilities]\n- Architect high-performance backend systems\n- Lead technical design for custody platforms\n- Mentor engineers and conduct code reviews\n\n[Requirements]\n- 7+ years backend experience\n- System architecture expertise\n- High-availability financial systems experience\n- Proficiency in Go, Rust, or Java'
t['615bbb5c-dc20-4e7a-9190-d0a5a04e7108'] = 'Vidacs builds core digital asset infrastructure including custody and settlement solutions.\n\n[Responsibilities]\n- Develop backend services for digital asset platform\n- Build APIs and blockchain integrations\n- Implement data processing systems\n\n[Requirements]\n- Backend development experience\n- Go, Node.js, or similar proficiency\n- Database design skills\n- Blockchain technology understanding'
t['3ed15691-ce50-4950-8acf-97f606ffe281'] = 'Genisoo operates CoworkCity, a shared office and startup support platform making entrepreneurship accessible.\n\n[Responsibilities]\n- Develop PropTech platform features as intern\n- Build frontend and backend components\n- Participate in agile development\n\n[Requirements]\n- CS/engineering student or recent graduate\n- Basic web development knowledge\n- Willingness to learn\n- Interest in PropTech'
t['cbe20474-bf69-4cd8-a722-867fe6ff7cb0'] = 'Willog is an AIoT logistics intelligence company combining hardware, software, and data to transform global logistics.\n\n[Responsibilities]\n- Manage corporate IT infrastructure and office systems\n- Administer internal tools, networks, security\n- Support employee IT onboarding and equipment\n\n[Requirements]\n- IT operations or system administration experience\n- Network infrastructure and security knowledge\n- IT asset management experience'
t['10a6c3d1-24d2-4f40-bba1-da361c40c924'] = 'Telepix develops satellite-based Earth observation solutions, extracting insights from space invisible to the human eye.\n\n[Responsibilities]\n- Develop computational optimization algorithms for satellite data\n- Design high-performance computing solutions\n- Optimize image processing and signal analysis pipelines\n\n[Requirements]\n- Mathematics, optimization, or computational science background\n- Numerical computing (Python/NumPy, C++)\n- Signal processing or image analysis knowledge\n- Parallel computing and GPU acceleration understanding'
t['cc166c7e-ccd8-41cd-9b82-3acc783f637f'] = 'LawTalk is Koreas No.1 legaltech startup, democratizing legal services through technology.\n\n[Responsibilities]\n- Build and maintain CI/CD pipelines\n- Manage cloud infrastructure (AWS/GCP)\n- Monitor system performance and reliability\n- Automate deployment processes\n\n[Requirements]\n- DevOps or SRE experience\n- Cloud platform experience\n- Docker, Kubernetes\n- CI/CD pipeline design\n- Infrastructure as Code'
t['a87268b1-4583-49e9-9deb-9ff3b3c58922'] = 'ShopLive is the No.1 global B2B/SaaS video commerce platform for live streaming e-commerce.\n\n[Responsibilities]\n- Design data pipelines and analytics infrastructure\n- Develop real-time data processing for video commerce\n- Build data models for business intelligence\n\n[Requirements]\n- 4+ years data engineering\n- SQL, Python, Spark\n- Streaming data (Kafka, Kinesis)\n- Data warehousing experience'
t['7e004c23-6e18-4ab0-a9b7-65d1415258d9'] = 'ShopLive is the No.1 global video commerce platform for live streaming e-commerce solutions.\n\n[Responsibilities]\n- Develop AI/ML models for video commerce\n- Build recommendation and personalization systems\n- Apply computer vision and NLP techniques\n\n[Requirements]\n- 3+ years AI/ML engineering\n- PyTorch or TensorFlow\n- Production ML deployment experience\n- Computer vision or NLP experience'
t['813fd623-80f9-4dc5-9f9f-347a018e2a95'] = 'ShopLive provides the leading global video commerce platform for enterprise live streaming.\n\n[Responsibilities]\n- Develop Android applications for video commerce SDK\n- Build real-time video streaming features\n- Optimize app performance\n\n[Requirements]\n- 4+ years Android development\n- Kotlin proficiency\n- Video/media processing experience\n- Android architecture patterns'
t['d5b4a629-236e-431c-9a74-b7ca84f84613'] = 'ShopLive delivers the leading B2B/SaaS video commerce platform.\n\n[Responsibilities]\n- Design backend services for video commerce\n- Build scalable APIs and microservices\n- Implement real-time data processing\n\n[Requirements]\n- 3+ years backend experience\n- Java, Kotlin, or Go\n- Microservice architecture\n- Database optimization'
t['946cb472-0d93-4d1e-a1a3-188db15f2556'] = 'ShopLive is the leading global video commerce platform for enterprise e-commerce.\n\n[Responsibilities]\n- Develop iOS applications for video commerce SDK\n- Build real-time video streaming for iOS\n- Optimize performance and memory\n\n[Requirements]\n- 4+ years iOS development\n- Swift proficiency\n- AVFoundation or video processing\n- iOS architecture patterns'
t['4cae60ca-d4e7-44f8-b4e7-4f38f3640421'] = 'ShopLive is the No.1 global B2B/SaaS video commerce platform.\n\n[Responsibilities]\n- Lead backend architecture for video commerce\n- Build high-scale distributed systems\n- Mentor team and establish best practices\n\n[Requirements]\n- 10+ years backend experience\n- Distributed systems expertise\n- Real-time streaming systems\n- Technical leadership experience'

let updated = 0
for (const [id, desc] of Object.entries(t)) {
  const { error } = await supabase.from('jobs').update({ description: desc }).eq('id', id)
  if (!error) updated++
  else console.log('ERR:', id, error.message)
}
console.log('Batch 3 done:', updated)
